language: python

python:
  - "3.4"
  - "3.2"
  - "2.7"

sudo: false

env:
  - DJANGO=1.4.20 FEINCMS=1.8.4
  - DJANGO=1.4.20 FEINCMS=1.9.2
  - DJANGO=1.7 FEINCMS=1.10.1
  - DJANGO=1.8 FEINCMS=1.11.0

install:
  - pip install -q Django==$DJANGO FeinCMS==$FEINCMS django-mptt==0.6.0 factory_boy==2.5.2 pytz==2013.8 flake8 --use-mirrors
  - python setup.py -q install

script: "cd tests && ./manage.py test testapp && flake8 ."

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.4.20 FEINCMS=1.8.4
    - python: "3.4"
      env: DJANGO=1.4.20 FEINCMS=1.9.2
    - python: "3.2"
      env: DJANGO=1.4.20 FEINCMS=1.8.4
    - python: "3.2"
      env: DJANGO=1.4.20 FEINCMS=1.9.2
    - python: "2.7"
      env: DJANGO=1.8 FEINCMS=1.11.0  # currently a bug in factory-boy
