language: python
cache: pip
sudo: false
python:
  - "3.4"
env:
  - REQ="Django>=1.8,<1.9 FeinCMS>=1.11,<1.12"
  - REQ="Django>=1.11,<2.0 FeinCMS>=1.13,<2"
  - REQ="Django>=2.0,<2.1 FeinCMS>=1.13,<2"
matrix:
  include:
    - python: "2.7"
      env: REQ="Django>=1.8,<1.9 FeinCMS>=1.11,<1.12"
    - python: "2.7"
      env: REQ="Django>=1.11,<2.0 FeinCMS>=1.13,<2"
install:
  - pip install $REQ django-mptt==0.9.0 factory_boy pytz flake8 Pillow
  - python setup.py install
script: "cd tests && ./manage.py test testapp && cd .. && flake8 ."
