language: python
cache: pip
python:
  - "3.4"
  - "2.7"
sudo: false
env:
  - REQ="Django>=1.8,<1.9 FeinCMS>=1.11,<1.12"
  - REQ="Django>=1.9,<1.10 FeinCMS>=1.13,<2"
  - REQ="Django>=1.10,<1.11 FeinCMS>=1.13,<2"
install:
  - pip install $REQ django-mptt==0.8.6 factory_boy pytz flake8 Pillow
  - python setup.py install
script: "cd tests && ./manage.py test testapp && cd .. && flake8 ."
