language: python

python:
  - "3.4"
  - "3.2"
  - "2.7"

sudo: false

env:
  - REQ="Django>=1.7,<1.8 FeinCMS>=1.11,<1.12"
  - REQ="Django>=1.8,<1.9 FeinCMS>=1.11,<1.12"
  - REQ="Django>=1.9,<1.10 https://github.com/feincms/feincms/archive/next.zip"
  - REQ="Django>=1.10,<1.11 https://github.com/feincms/feincms/archive/next.zip"

install:
  - pip install -q $REQ django-mptt==0.8.6 factory_boy pytz flake8 Pillow
  - python setup.py -q install

script: "cd tests && ./manage.py test testapp && cd .. && flake8 ."
