language: python

python:
  - "3.4"
  - "3.2"
  - "2.7"

sudo: false

env:
  - DJANGO=1.7 FEINCMS=1.11
  - DJANGO=1.8 FEINCMS=1.11
  - DJANGO=1.7 FEINCMS=2.0a2
  - DJANGO=1.8 FEINCMS=2.0a2

install:
  - pip install -q Django==$DJANGO FeinCMS==$FEINCMS django-mptt==0.6.0 factory_boy==2.2.1 pytz==2013.8 flake8 --use-mirrors
  - python setup.py -q install

script: "cd tests && ./manage.py test testapp && flake8 ."
